apiVersion: v1
kind: Service
metadata:
  name: expense-track-service
spec:
  selector:
    app: expense-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
